### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by Retky** [Retky/SpaceTravelers#26]
### Following the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md):
- We are a team of two
- The link to our project Kanban: 
[https://github.com/Retky/SpaceTravelers/projects/1](https://github.com/Retky/SpaceTravelers/projects/1)

**Comment by Meltrust** [comment]
Hi @Retky,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Nice work distribution ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/167490422-b6db16ab-8991-403e-abd2-c5c37e13f634.png)

You have tasks without people assigned to them (the group tasks). 
![image](https://user-images.githubusercontent.com/57421823/167490683-cd97f70d-2cd9-4bfa-acad-21f77a964c13.png)


Therefore:

- [ ] Please, assign people to all the cards.  You could assign both team members to the group tasks if desired.  Just make sure every task, including the group tasks, has at least one assignee.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
